language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: AGCEccXiEGCaaAoA4+7ZiCJptGOe347rgROXBmoGMd8HewjA628aYWF+mI9pq4AjWsSocEfvyD4DF79kTzwLFvxlk6PQ80soV2UqEjBcY1KnB+gxC5Mn0r/M6INJUY47HzSSwlVbLb+MEKlEUYA3+zNfk+L5x3ssU4vmWHcujEFw3tndjgMT0DJluDkfjM19FomnSKTAhUvVUfCGNp29HyrUg+oJEoD99zRNm1/ogcGrHxrLLYN4C/IWGM8X8mCrxxs0CcRbg/U8q52wtaodNA2fdTkEKZTa5qVXdE0DOhPPRn3tBm/i1aYMfDXcFBTyHZxcds91/OBOEbqnWSi+Ryudomyu2/U9XtAd7VSKS4YdnoJNV0boUuMK61u0skHO5roVruYR0MVaHrIu2FAUH+CI0BVLpM6pA8DvwS/OGDDrBy7A986OVavB6DPbyX7bI1yQpYtNqxD1g+bfbV4jeGSAliJ609DsNSaSjZjXeJMvqN6eRl3H7ybuct3wEFIaa/ua1Tvff0UadPTDd4OOM4imJfbhaEJhXbccjf30HcJDd/jpheA5EHHcHeFO49DwapES1ApRI/2vNGFGX0ufSoMnWCi3N5ztJO2mRyFWmi62CD/jHSe1eCbscKoJJfdEMes+/UtYCEjCZOK51MHKAVQlA0PFifWFZLpoOZdzGjw=
  file:
    - 'hast-util-menu-state.js'
    - 'hast-util-menu-state.min.js'
  on:
    tags: true
