language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: hZHi1o5z51PwY2Zx8pmMR1qhLPseHByo3CqUl0ZQolSlkLsTdf+hF1s6fgefM6EIAGOX0ROwitb3Gu75epOKFuV1Khxy55qqqoE7aRQUNkbpdo9ZCVL895pcAIWFBgbHoCR4xRpghg184xaYZbDBviWQnktJXrIFMPE9IObUZPEzbYAu4En1f/3bthzbbSNuh80v9Jrl4Z7rQr0nhwPTAWtAR29dBydZDjMnNkjZ2pUc97i2zIz4hiuP2AUIVtFF0kAp4NUgN26bLlvJ/HAMTC6waPruqmANdOccW9bqDYtRZpVIsWnRytC2c/Ipz62Zgc3ZcA+Dd5FfDCtvfA2wCzuC6BREFffRpIgGVuxRLo7SFdIfO1CsjKL4QQPPoCbhxLARIo+12kXFt6eMZCuOu99S8ZjO3eMJUoCiF8Rf5HzulmBmkYKDJ02dbTCjUL2D26KJM/wTUzIMtLu14bQ46sM+ZvfjDF/uwBwc2/X3fsH0TJaZBDKG+a69DFmuZMuwQY6bP8vZL/x7VMqMNGTsxMGMzCdNh+guRoXZ1R5VBDhTS5kdQEKTD+viZPEzeQTE2GrIkQejfKV6aL4uuiAPlOPTCeqrCXxNdFRNheOma0usa1fmx0OIASAammD305k9YHGaryWlaYl1nUCCl52TYLQDABSM7yMWH6pqq4fDjlI=
  file:
    - "hast-util-menu-state.js"
    - "hast-util-menu-state.min.js"
  on:
    tags: true
